name: Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
      ALGOLIA_ID: ${{ secrets.ALGOLIA_ID }}
      GA_ID: ${{ secrets.GA_ID }}
      HOTJAR_ID: ${{ secrets.HOTJAR_ID }}

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@master
        with:
          node-version: 16.14.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: .

      - name: Build static
        run: yarn build
        working-directory: .

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./build