name: Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
      ALGOLIA_ID: ${{ secrets.ALGOLIA_ID }}
      GA_ID: ${{ secrets.GA_ID }}
      HOTJAR_ID: ${{ secrets.HOTJAR_ID }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: .

      - name: Retrieve Docusaurus build cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/webpack
          key: ${{ runner.os }}-docusaurus

      - name: Build static
        run: pnpm build
        working-directory: .

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./build
