name: Run tests

on:
  - pull_request

jobs:
  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
      ALGOLIA_ID: ${{ secrets.ALGOLIA_ID }}
      GA_ID: ${{ secrets.GA_ID }}
      HOTJAR_ID: ${{ secrets.HOTJAR_ID }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: pnpm install
        working-directory: .

      - name: Retrieve Docusaurus build cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/webpack
          key: ${{ runner.os }}-docusaurus

      - name: Check build
        run: pnpm build
        working-directory: .

  test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: pnpm install
        working-directory: .

      - name: Check linting
        run: pnpm run test:lint
        working-directory: .
